name: Terraform CI

on:
  pull_request:
    branches:
      - main
      -
jobs:
  terraform:
    name: Terraform Format and Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate
